### ISSUE TITLE
Website https://percival.ink/ doesnt load on Firefox

### ISSUE THREAD

**Issue by aurabindo** [ekzhang/percival#10] opened 2021-12-12 14:43 UTC
I see a white page if I open https://percival.ink/ in Firefox 78.15 (From Debian repo). But it works fine on Chrome

**Comment by ekzhang** [comment] 2021-12-12 15:03
Thanks for the bug report! I don't think I can reproduce (it works for Firefox on macOS), but Percival does use a lot of bleeding-edge web technologies.

If you have time, could you let me know what version of Firefox you're using and send a screenshot of any errors in your developer console?

**Comment by ekzhang** [comment] 2021-12-12 16:46
Ah, it looks like top-level await isn't supported in Firefox versions below v89, according to [caniuse.com](https://caniuse.com/?search=top-level%20await). 

![image](https://user-images.githubusercontent.com/7550632/145721290-18a75a22-f538-46bb-bc0a-99fb4d45b465.png)

Unfortunately, since Percival is an early research project and not an enterprise product, I don't believe it's my goal right now to support non-evergreen browsers, so I'm going to close this issue. If you're still running into a white screen, please update your browser version.

**Closed by ekzhang** 2021-12-12 16:46 UTC
